# Generated by Django 3.1.2 on 2021-09-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post',
            name='active',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='age',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='breed',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='dog_name',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='friendly',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='gender',
            field=models.TextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='health',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='kids',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='size',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='org_name',
            field=models.TextField(blank=True, max_length=150),
        ),
    ]
